app:
   build: .
tomcat:
  image: infrabricks/tomcat:8
  ports:
    - "8080"
    - "8009"
  volumes_from:
    - app
  volumes:
    - tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    constraint: zone==dev
    constraint: disk==ssd
    SERVICE_8080_NAME: qr-http
    SERVICE_8009_NAME: qr-ajp
    SERVICE_TAGS: tomcat
    SERVICE_REGION: bee42.1
