mysql:
  image: mysql:5.6
  volumes:
    - mysql/etc/mysql:/etc/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: emp
    MYSQL_PASSWORD: emp
    MYSQL_DATABASE: emp
emp:
  build: .
  ports:
    - "8080"
  links:
    - mysql
  environment:
    constraint: zone==dev
    constraint: affinity:container==emp_mysql_1
    SERVICE_8080_NAME: emp
    SERVICE_TAGS: tomcat emp
    SERVICE_REGION: bee42.1
    MYSQL_USER: emp
    MYSQL_PASSWORD: emp
    MYSQL_DATABASE: emp
